# GET the home route
GET http://localhost:5678/

### GET the tests route
GET http://localhost:5678/tests/

### GET the tests route invalid id
GET http://localhost:5678/tests/moihei

### GET the tests route id 0
GET http://localhost:5678/tests/0

### GET the tests route id 0 submissions
GET http://localhost:5678/tests/0/submissions

